server:
  port: 8010
  compression:
    enabled: true
    #    mime-types:
    #      - application/json
    #      - application/xml
    #      - text/html
    #      - text/xml
    #      - text/plain
    min-response-size: 1
spring:
  profiles:
    active: dev
  application:
    name: alicloud-web
  config:
    import:
      - optional:nacos:${spring.application.name}
      #   - nacos:${spring.application.name}.yml
      - optional:nacos:alicloud-common
    #      - optional:classpath:application-common.yml.bak
    #        - optional:nacos:app.yml?group=DEFAULT_GROUP&namespace=3b23975d-2d7c-40bc-b09b-81c1c02a61a1&refreshEnabled=true
    #        - optional:nacos:globalConfig.yml?group=DEFAULT_GROUP&namespace=3b23975d-2d7c-40bc-b09b-81c1c02a61a1&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: 111.170.11.134:8848
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        #        namespace: f79f8608-266c-4bb9-922d-03e5e76823d6
        username: ENC(2BuGrwjx09OwzgvJOKmAqI2qZmE/tTobMUjkig8YR7lofvVPX8H+w5z9lv2F1sKY)
        # zzl19920901
        password: ENC(oZ5LqYwdeXnrQLsllPWUjdGUDZT6b1wlphlYm3pQynTxV2wRhBdfdBwwLu6SnW/H)
        namespace: 02f2ce9c-4630-4ea0-9eaf-aa7dfc818af7
      config:
        server-addr: 111.170.11.134:8848
        #        import-check:
        #          enabled: false
        namespace: 02f2ce9c-4630-4ea0-9eaf-aa7dfc818af7
        group: DEFAULT_GROUP
#        username: ENC(2BuGrwjx09OwzgvJOKmAqI2qZmE/tTobMUjkig8YR7lofvVPX8H+w5z9lv2F1sKY)
#        password: ENC(oZ5LqYwdeXnrQLsllPWUjdGUDZT6b1wlphlYm3pQynTxV2wRhBdfdBwwLu6SnW/H)
        username: ${NACOS_USER_NAME}
        password: ${NACOS_USER_PASSWORD}
        file-extension: yaml

jasypt:
  encryptor:
    password: H31ThYM0n1t0r
