############################################################
# #mybatis 配置
# #
###########################################################
#mybatis-plus:
#  configuration:
#    #开启驼峰命名自动映射
#    map-underscore-to-camel-case: true
#    #开启日志打印
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    default-enum-type-handler: com.alicloud.config.mybatis.handler.CommonEnumTypeHandler
#  type-aliases-package: com.alicloud.bean  # 所有POJO类所在包路径
#  #扫描mapper文件
#  mapper-locations: classpath:mappings/*.xml