# 生产环境配置
server:
  port: 8010

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_URL}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:zzl19920901}
        namespace: ${NACOS_NAMESPACE:prod}
      config:
        server-addr: ${NACOS_SERVER_URL}
        namespace: ${NACOS_NAMESPACE:prod}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:zzl19920901}
        file-extension: yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_CONNECT_URL}/op_db?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: ${DB_USERNAME:zzl}
    password: ${DB_PASSWORD:1qaz!QAZ}
    hikari:
      connection-timeout: 30000
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

logging:
  level:
    root: warn
    com.alicloud: info